heat_template_version: 2016-10-14

resources:
  vanilla_cluster_template:
    type: OS::Sahara::ClusterTemplate
    properties:
      default_image_id: d9c94c74-5aa0-4f01-be05-c0aa78a5f3fe
      description: Vanilla hadoop cluster template
      hadoop_version: 2.7.1
      name: hadoop-cluster-template
      neutron_management_network: private
      node_groups: [{"name": "master", "count": 1, "node_group_template_id": "050a7318-b6f5-4971-b258-3172f52a237c"}, {"name": "workers", "count": 3, "node_group_template_id": "05767d42-1ba4-4cfc-a5de-2e03c6dccebc"}]
      plugin_name: vanilla
      use_autoconfig: True