heat_template_version: 2016-10-14

parameters:
  admin_id:
    label: Admin ID
    type: string
    description: Admin ID for base image
    default: centos
  image_tags:
    label: Image tags
    type: comma_delimited_list
    description: Comma-delimited list of image tags
    default: [ "vanilla", "2.7.1" ]
  image_url:
    label: Image URL
    type: string
    description: URL for Sahara image to upload to Glance and register in Sahara
    default: http://sahara-files.mirantis.com/images/upstream/newton/sahara-newton-vanilla-2.7.1-centos7.qcow2
  image_name:
    label: Image Name
    type: string
    description: Image name in Glance
    default: vanilla-hadoop-2.7.1

resources:
  glance_image:
    type: OS::Glance::Image
    properties:
      container_format: bare
      disk_format: qcow2
      is_public: true
      location: { get_param: image_url }
      name: { get_param: image_name }

  vanilla_image:
    type: OS::Sahara::ImageRegistry
    depends_on: glance_image
    properties:
      description: Sahara Vanilla Hadoop Image
      image: { get_resource: glance_image }
      tags: { get_param: image_tags }
      username: { get_param: admin_id }

outputs:
  glance_image_id:
    description: Image ID for image downloaded to glance
    value: { get_attr: [ glance_image, show, id ]}