heat_template_version: 2016-10-14

parameters:
  image_id:
    label: Image ID
    type: string
    description: Glance image ID to register in Sahara
    default: d9c94c74-5aa0-4f01-be05-c0aa78a5f3fe
  admin_id:
    label: Admin ID
    type: string
    description: Admin ID for base image
    default: centos
  image_tags:
    label: Image tags
    type: comma_delimited_list
    description: Comma-delimited list of image tags
    default: [ "vanilla", "2.7.1" ]

resources:
  vanilla_image:
    type: OS::Sahara::ImageRegistry
    properties:
      description: Sahara Vanilla Hadoop Image
      image: { get_param: image_id }
      tags: { get_param: image_tags }
      username: { get_param: admin_id }
