heat_template_version: 2016-10-14

resources:
  vanilla_image:
    type: OS::Sahara::ImageRegistry
    properties:
      description: Sahara Vanilla Hadoop Image
      image: d9c94c74-5aa0-4f01-be05-c0aa78a5f3fe
      tags: [ "vanilla", "2.7.1" ]
      username: "centos"
