heat_template_version: 2016-10-14

parameters:
  image_id:
    label: Image ID
    type: string
    description: Glance image ID to register in Sahara
    default: d9c94c74-5aa0-4f01-be05-c0aa78a5f3fe

resources:
  vanilla_hadoop_master_node:
    type: OS::Sahara::NodeGroupTemplate
    properties:
      auto_security_group: True
      availability_zone: nova
      description: Vanilla Hadoop master node group template
      flavor: m1.medium
      floating_ip_pool: nova
      hadoop_version: 2.7.1
      image_id: { get_param: image_id }
      is_proxy_gateway: False
      name: Hadoop-Master-Node
      node_processes: ["namenode", "secondarynamenode", "resourcemanager", "historyserver", "oozie"]
      plugin_name: "vanilla"
      security_groups: ["default"]
      use_autoconfig: True

  vanilla_hadoop_worker_node:
    type: OS::Sahara::NodeGroupTemplate
    properties:
      auto_security_group: True
      availability_zone: nova
      description: Vanilla Hadoop worker node group template
      flavor: m1.large
      floating_ip_pool: nova
      hadoop_version: 2.7.1
      image_id: { get_param: image_id }
      is_proxy_gateway: False
      name: Hadoop-Worker-Node
      node_processes: ["nodemanager", "datanode"]
      plugin_name: "vanilla"
      security_groups: ["default"]
      use_autoconfig: True