
parameter_defaults:
  node_key_name: mykey
  image_url: http://sahara-files.mirantis.com/images/upstream/newton/sahara-newton-vanilla-2.7.1-centos7.qcow2
  image_name: vanilla-hadoop-2.7.1
  admin_id: centos
  image_tags: [ "vanilla", "2.7.1" ]
  master_node_count: 1
  worker_node_count: 3
  master_node_flavor: m1.medium
  worker_node_flavor: m1.large