heat_template_version: 2016-10-14

parameters:
  image_id:
    label: Image ID
    type: string
    description: Glance image ID
  master_node_template_id:
    label: Master node template ID
    type: string
    description: UUID for master nodegroup template
    default: 050a7318-b6f5-4971-b258-3172f52a237c
  worker_node_template_id:
    label: Worker node template ID
    type: string
    description: UUID for worker nodegroup template
    default: 05767d42-1ba4-4cfc-a5de-2e03c6dccebc
  master_node_count:
    label: Master Node Count
    type: integer
    description: Number of master nodes in cluster
    default: 1
  worker_node_count:
    label: Worker node count
    type: integer
    description: Number of worker nodes in cluster
    default: 3

resources:
  vanilla_cluster_template:
    type: OS::Sahara::ClusterTemplate
    properties:
      default_image_id: { get_param: image_id }
      description: Vanilla hadoop cluster template
      hadoop_version: 2.7.1
      name: hadoop-cluster-template
      neutron_management_network: private
      node_groups:
        - name: "master"
          count: { get_param: master_node_count }
          node_group_template_id: { get_param: master_node_template_id }
        - name: "workers"
          count: { get_param: worker_node_count }
          node_group_template_id: { get_param: worker_node_template_id }
      plugin_name: vanilla
      use_autoconfig: True

outputs:
  template_id:
    description: UUID for cluster template
    value: { get_attr: [ vanilla_cluster_template, show, id ] }