heat_template_version: 2016-10-14

parameters:
  password:
    type: string
  user:
    type: string

resources:
  pig_tutorial_input:
    type: OS::Sahara::DataSource
    properties:
      description: Input data for PIG tutorial
      name: pig_tutorial_input
      type: swift
      url: swift://pig-tutorial.sahara/excite.log.bz2
      credentials: {"password": { get_param: password }, "user": { get_param: user } }

  pig_tutorial_output:
    type: OS::Sahara::DataSource
    properties:
      description: Output location for PIG tutorial
      name: pig_tutorial_output
      type: swift
      url: swift://pig-tutorial.sahara/output
      credentials: {"password": { get_param: password }, "user": { get_param: user } }
